# Generated by Django 5.1.4 on 2025-05-24 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ispb', models.CharField(max_length=254)),
                ('nome_reduzido', models.TextField()),
                ('nome', models.CharField(max_length=254)),
                ('codigo_compensacao', models.IntegerField()),
                ('site', models.CharField(max_length=254)),
                ('email', models.CharField(max_length=254)),
                ('outras_informacoes', models.TextField()),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
            },
        ),
        migrations.CreateModel(
            name='Investigado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('cpf_cnpj', models.IntegerField(unique=True)),
                ('tipo', models.CharField(choices=[('fisica', 'Física'), ('juridica', 'Jurídica')], max_length=254)),
                ('dados_pessoais', models.TextField()),
                ('enderecos', models.TextField()),
                ('observacoes', models.TextField()),
            ],
            options={
                'verbose_name': 'Investigado',
                'verbose_name_plural': 'Investigados',
            },
        ),
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.IntegerField()),
                ('tipo', models.CharField(max_length=254)),
                ('nome', models.CharField(max_length=254)),
                ('hash', models.CharField(max_length=254)),
                ('registros', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.caso')),
            ],
            options={
                'verbose_name': 'Arquivo',
                'verbose_name_plural': 'Arquivos',
            },
        ),
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('agencia', models.CharField(max_length=254)),
                ('nome_agencia', models.CharField(max_length=254)),
                ('endereco', models.CharField(max_length=254)),
                ('numero', models.CharField(max_length=50)),
                ('complemento', models.CharField(max_length=254)),
                ('bairro', models.CharField(max_length=254)),
                ('cep', models.CharField(max_length=9)),
                ('municipio', models.CharField(max_length=254)),
                ('uf', models.CharField(max_length=2)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=254)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.banco')),
            ],
            options={
                'verbose_name': 'Agência',
                'verbose_name_plural': 'Agências',
            },
        ),
    ]
