# Generated by Django 5.1.4 on 2025-05-24 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_banco_investigado_arquivo_agencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasoInvestigado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigados', to='app.caso')),
                ('investigado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='app.investigado')),
            ],
            options={
                'verbose_name': 'CasoInvestigado',
                'verbose_name_plural': 'CasosInvestigados',
                'unique_together': {('caso', 'investigado')},
            },
        ),
    ]
