# Generated by Django 5.1.4 on 2025-08-08 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_relatorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], max_length=254),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='tipo',
            field=models.CharField(choices=[('financeiro', 'Financeiro'), ('bancaria', 'Bancária'), ('patrimonial', 'Patrimonial')], max_length=254),
        ),
    ]
