# Generated by Django 5.1.4 on 2025-07-11 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0003_casoinvestigado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ispb', models.CharField(max_length=254)),
                ('nome_reduzido', models.TextField()),
                ('nome', models.CharField(max_length=254)),
                ('codigo_compensacao', models.IntegerField()),
                ('site', models.CharField(max_length=254)),
                ('email', models.CharField(max_length=254)),
                ('outras_informacoes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BancoAgencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia', models.CharField(max_length=254)),
                ('nome_agencia', models.CharField(max_length=254)),
                ('endereco', models.CharField(max_length=254)),
                ('numero', models.CharField(max_length=50)),
                ('complemento', models.CharField(max_length=254)),
                ('bairro', models.CharField(max_length=254)),
                ('cep', models.CharField(max_length=9)),
                ('municipio', models.CharField(max_length=254)),
                ('uf', models.CharField(max_length=2)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=254)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bancaria.banco')),
            ],
        ),
        migrations.CreateModel(
            name='Cooperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=254)),
                ('inquerito', models.CharField(max_length=254)),
                ('processo', models.CharField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooperacoes_bancarias', to='app.caso')),
            ],
        ),
        migrations.CreateModel(
            name='ExtratoDetalhado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.IntegerField()),
                ('numero_agencia', models.IntegerField()),
                ('numero_conta', models.IntegerField()),
                ('tipo', models.IntegerField()),
                ('nome_titular', models.CharField(max_length=254)),
                ('cpf_cnpj_titular', models.CharField(max_length=254)),
                ('descricao_lancamento', models.CharField(max_length=254)),
                ('cnab', models.CharField(max_length=254)),
                ('data_lancamento', models.DateField()),
                ('numero_documento', models.CharField(max_length=254)),
                ('numero_documento_transacao', models.CharField(max_length=254)),
                ('local_transacao', models.CharField(max_length=254)),
                ('valor_transacao', models.FloatField()),
                ('natureza_lancamento', models.CharField(max_length=10)),
                ('valor_saldo', models.FloatField()),
                ('natureza_saldo', models.CharField(choices=[('C', 'Crédito'), ('D', 'Débito')], max_length=1)),
                ('cpf_cnpj_od', models.CharField(max_length=254)),
                ('nome_pessoa_od', models.CharField(max_length=254)),
                ('tipo_pessoa_od', models.CharField(max_length=254)),
                ('numero_banco_od', models.IntegerField()),
                ('numero_agencia_od', models.IntegerField()),
                ('numero_conta_od', models.IntegerField()),
                ('observacao', models.CharField(max_length=254)),
                ('nome_endossante_cheque', models.CharField(max_length=254)),
                ('doc_endossante_cheque', models.CharField(max_length=254)),
                ('arquivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.arquivo')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.caso')),
                ('cooperacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bancaria.cooperacao')),
            ],
        ),
    ]
