# Generated by Django 5.1.4 on 2025-08-08 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extratodetalhado',
            name='banco',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='extratodetalhado',
            name='numero_agencia',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='extratodetalhado',
            name='numero_agencia_od',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='extratodetalhado',
            name='numero_banco_od',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='extratodetalhado',
            name='numero_conta',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='extratodetalhado',
            name='numero_conta_od',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='extratodetalhado',
            name='tipo',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
