# Generated by Django 5.1.4 on 2025-08-12 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_planos_iniciais'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assinatura',
            old_name='faces',
            new_name='casos',
        ),
        migrations.RemoveField(
            model_name='assinatura',
            name='reconhecimentos',
        ),
        migrations.RemoveField(
            model_name='planos',
            name='faces',
        ),
        migrations.RemoveField(
            model_name='planos',
            name='reconhecimentos',
        ),
        migrations.AddField(
            model_name='planos',
            name='casos',
            field=models.IntegerField(default=0, help_text='Cota total de casos para o período do plano'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planos',
            name='limite_usuarios',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=50)),
                ('complemento', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidade_created_by', to=settings.AUTH_USER_MODEL)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidade_instituicao', to='user.instituicao')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidade_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidade_usuario', to='user.unidade'),
        ),
    ]
