# Generated by Django 5.1.4 on 2025-08-24 22:25

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_rename_faces_assinatura_casos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[user.models.validate_mpce_email]),
        ),
    ]
