# Generated by Django 5.1.4 on 2025-05-24 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_banco_investigado_arquivo_agencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=12)),
                ('nome', models.TextField()),
                ('arquivo', models.TextField()),
            ],
            options={
                'verbose_name': 'Plugin',
                'verbose_name_plural': 'Plugins',
            },
        ),
        migrations.CreateModel(
            name='Comunicacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('indexador', models.IntegerField()),
                ('id_comunicacao', models.IntegerField()),
                ('numero_ocorrencia_bc', models.CharField(max_length=254)),
                ('data_recebimento', models.CharField(max_length=254)),
                ('data_operacao', models.CharField(max_length=254)),
                ('data_fim_fato', models.CharField(max_length=254)),
                ('cpf_cnpj_comunicante', models.IntegerField()),
                ('nome_comunicante', models.CharField(max_length=254)),
                ('cidade_agencia', models.CharField(max_length=254)),
                ('uf_agencia', models.CharField(max_length=2)),
                ('nome_agencia', models.CharField(max_length=254)),
                ('numero_agencia', models.IntegerField()),
                ('informacoes_adicionais', models.TextField()),
                ('campo_a', models.TextField()),
                ('campo_b', models.TextField()),
                ('campo_c', models.TextField()),
                ('campo_d', models.TextField()),
                ('campo_e', models.TextField()),
                ('codigo_segmento', models.IntegerField()),
                ('arquivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.arquivo')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.caso')),
            ],
            options={
                'verbose_name': 'Comunicacaoo',
                'verbose_name_plural': 'Comunicacoes',
            },
        ),
        migrations.CreateModel(
            name='Cooperacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=254)),
                ('inquerito', models.CharField(max_length=254)),
                ('processo', models.CharField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.caso')),
            ],
            options={
                'verbose_name': 'Cooperacao',
                'verbose_name_plural': 'Cooperacoes',
            },
        ),
        migrations.CreateModel(
            name='RIF',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=254)),
                ('outras_informacoes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.caso')),
            ],
            options={
                'verbose_name': 'RIF',
                'verbose_name_plural': 'RIFs',
            },
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('indexador', models.IntegerField()),
                ('id_ocorrencia', models.IntegerField()),
                ('ocorrencia', models.TextField()),
                ('arquivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.arquivo')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.caso')),
                ('rif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeira.rif')),
            ],
            options={
                'verbose_name': 'Ocorrencia',
                'verbose_name_plural': 'Ocorrencias',
            },
        ),
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('indexador', models.IntegerField()),
                ('profissao', models.CharField(max_length=254)),
                ('renda', models.FloatField()),
                ('periodo', models.CharField(max_length=254)),
                ('analise', models.TextField()),
                ('arquivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.arquivo')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.caso')),
                ('comunicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeira.comunicacao')),
                ('rif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeira.rif')),
            ],
            options={
                'verbose_name': 'KYC',
                'verbose_name_plural': 'KYCs',
            },
        ),
        migrations.CreateModel(
            name='InformacaoAdicional',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('indexador', models.IntegerField()),
                ('tipo_transacao', models.IntegerField()),
                ('cpf', models.IntegerField()),
                ('nome', models.TextField()),
                ('valor', models.FloatField()),
                ('transacoes', models.IntegerField()),
                ('plataforma', models.CharField(max_length=254)),
                ('arquivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.arquivo')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.caso')),
                ('comunicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeira.comunicacao')),
                ('rif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeira.rif')),
            ],
            options={
                'verbose_name': 'InformacaoAdicional',
                'verbose_name_plural': 'InformacoesAdicionais',
            },
        ),
        migrations.CreateModel(
            name='Envolvido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('indexador', models.IntegerField()),
                ('cpf_cnpj_envolvido', models.IntegerField()),
                ('nome_envolvido', models.CharField(max_length=254)),
                ('tipo_envolvido', models.CharField(max_length=254)),
                ('agencia_envolvido', models.IntegerField()),
                ('conta_envolvido', models.IntegerField()),
                ('data_abertura_conta', models.DateField()),
                ('data_atualizacao_conta', models.DateField()),
                ('bit_pep_citado', models.CharField(max_length=3)),
                ('bit_pessoa_obrigada_citado', models.CharField(max_length=3)),
                ('int_servidor_citado', models.CharField(max_length=3)),
                ('arquivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.arquivo')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.caso')),
                ('rif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeira.rif')),
            ],
            options={
                'verbose_name': 'Envolvido',
                'verbose_name_plural': 'Envolvidos',
            },
        ),
        migrations.CreateModel(
            name='ComunicacaoNaoProcessada',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('indexador', models.IntegerField()),
                ('nome_comunicante', models.TextField()),
                ('arquivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.arquivo')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.caso')),
                ('rif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeira.rif')),
            ],
            options={
                'verbose_name': 'ComunicacaoNaoProcessada',
                'verbose_name_plural': 'ComunicacoesNaoProcessadas',
            },
        ),
        migrations.AddField(
            model_name='comunicacao',
            name='rif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeira.rif'),
        ),
    ]
