# Generated by Django 5.1.4 on 2025-05-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeira', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacaoadicional',
            name='cpf',
            field=models.CharField(max_length=21),
        ),
        migrations.AlterField(
            model_name='informacaoadicional',
            name='tipo_transacao',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='informacaoadicional',
            name='transacoes',
            field=models.CharField(max_length=254),
        ),
    ]
