# Generated by Django 5.1.4 on 2025-07-10 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeira', '0002_alter_informacaoadicional_cpf_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(help_text='Módulo onde o prompt é usado (ex: financeira)', max_length=100)),
                ('funcao', models.CharField(help_text='Função específica onde o prompt é usado (ex: comunicacao_detalhes)', max_length=100)),
                ('label', models.CharField(help_text='Nome amigável do prompt para exibição ao usuário', max_length=200)),
                ('prompt', models.TextField(help_text='Conteúdo do prompt')),
                ('old_versions', models.JSONField(blank=True, default=list, help_text='Versões anteriores do prompt')),
                ('is_active', models.BooleanField(default=True, help_text='Se o prompt está ativo')),
                ('description', models.TextField(blank=True, help_text='Descrição detalhada do que o prompt faz')),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Parâmetros esperados pelo prompt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Usuário que criou o prompt', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prompt',
                'verbose_name_plural': 'Prompts',
                'db_table': 'prompts',
                'unique_together': {('modulo', 'funcao', 'label')},
            },
        ),
    ]
