# Generated by Django 5.1.4 on 2025-07-11 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeira', '0003_prompt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cooperacao',
        ),
    ]
