# Generated by Django 5.1.4 on 2025-08-01 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeira', '0004_delete_cooperacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envolvido',
            name='agencia_envolvido',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='envolvido',
            name='bit_pep_citado',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='envolvido',
            name='bit_pessoa_obrigada_citado',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='envolvido',
            name='conta_envolvido',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='envolvido',
            name='data_abertura_conta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='envolvido',
            name='data_atualizacao_conta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='envolvido',
            name='int_servidor_citado',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
