# Generated by Django 5.1.4 on 2025-08-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeira', '0006_analiseia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envolvido',
            name='cpf_cnpj_envolvido',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
