# Generated by Django 5.1.4 on 2025-08-27 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeira', '0007_alter_envolvido_cpf_cnpj_envolvido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicacao',
            name='cpf_cnpj_comunicante',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='envolvido',
            name='cpf_cnpj_envolvido',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
